### ISSUE TITLE
Install step issue

### ISSUE THREAD

**Issue by dujiaoshou1022** [ArthurChiao/vim_awesome#8]
Can't find the shell script file in the repo and fail to install by the following steps

# it's better to backup your old configuration files
$ cd ~ && mkdir vimback && mv .vim* vimback -rf

# clone repo
$ git clone --depth 1 https://github.com/ArthurChiao/vim_awesome.git

# copy files to home directory
$ cd vim_awesome && cp .vim_runtime ~ -rf

# install
$ sh ~/.vim_runtime/install_awesome_vimrc.sh

![image](https://github.com/ArthurChiao/vim_awesome/assets/19722348/c84f3c6c-1ede-464f-9745-4ac9e56dd9ce)

**Comment by ArthurChiao** [comment]
@dujiaoshou1022  Sorry for late response, I'm still using this vim config, but actually haven't paid attention to the README materials for years, just fixed it (but there may be other broken steps) :(
